import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from "next/font/local";

const kiwiMaru = localFont({
  src: [
    {
      path: "../public/fonts/KiwiMaru-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/KiwiMaru-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/KiwiMaru-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  display: "swap",
});


export const metadata: Metadata = {
  title: "1分でできるはじめて防災診断",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${kiwiMaru.className} text-[#523B10]`}>
        <Header />
        {/* 全ページ共通の外枠（CSSクラス使用） */}
        <main className="full-page-container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
